name: Rust CI

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: check
                  args: --all-features

    test:
        name: Test Suite
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --all-features

    fmt:
        name: Rustfmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: rustfmt
            - uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
                  components: clippy
            - uses: actions-rs/cargo@v1
              with:
                  command: clippy
                  args: --all-features -- -D warnings

    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - name: Install cargo-tarpaulin
              uses: actions-rs/install@v0.1
              with:
                  crate: cargo-tarpaulin
                  version: latest
                  use-tool-cache: true
            - name: Run cargo-tarpaulin
              uses: actions-rs/cargo@v1
              with:
                  command: tarpaulin
                  args: --out Xml --verbose
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: false

    build-linux:
        name: Build Linux
        runs-on: ubuntu-latest
        needs: [check, test, fmt, clippy]
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - uses: actions/upload-artifact@v4
              with:
                  name: AutoCV-linux
                  path: target/release/AutoCV

    build-macos:
        name: Build macOS
        runs-on: macos-latest
        needs: [check, test, fmt, clippy]
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - uses: actions/upload-artifact@v4
              with:
                  name: AutoCV-macos
                  path: target/release/AutoCV

    build-windows:
        name: Build Windows
        runs-on: windows-latest
        needs: [check, test, fmt, clippy]
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release
            - uses: actions/upload-artifact@v4
              with:
                  name: AutoCV-windows
                  path: target/release/AutoCV.exe
